name: ndc-realisations-2021
channels:
  - conda-forge
dependencies:
  - pip
  - notebook
  - ipywidgets
  - numpy
  - nbformat>=5.0.2
  - pandas==1.3.0
  - matplotlib
  - seaborn
  - simplejson
  - scmdata==0.13.1
  - pymagicc
  - pyam
  - pyyaml
  - netcdf4
  - tqdm
  - nb_black
  - pip:
    - jedi==0.17.2
    - silicone
    - openscm-units==0.5.0
    - pytest